// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(JUGContext))]
    [Migration("20200417193922_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.DAO.CompetitionDAO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Data.DAO.GameDAO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AwayId")
                        .HasColumnType("bigint");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayShots")
                        .HasColumnType("int");

                    b.Property<bool>("CanTie")
                        .HasColumnType("bit");

                    b.Property<long?>("CompetitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<long?>("HomeId")
                        .HasColumnType("bigint");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeShots")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOverTimePeriods")
                        .HasColumnType("int");

                    b.Property<int>("NormalPeriods")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Data.DAO.TeamDAO", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.Property<int>("TeamType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TeamDAO");
                });

            modelBuilder.Entity("Data.DAO.SeasonTeamDAO", b =>
                {
                    b.HasBaseType("Data.DAO.TeamDAO");

                    b.Property<long?>("CompetitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("OverTimeLoses")
                        .HasColumnType("int");

                    b.Property<int>("OverTimeWins")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("RegulationLoses")
                        .HasColumnType("int");

                    b.Property<int>("RegulationWins")
                        .HasColumnType("int");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("ShotsFor")
                        .HasColumnType("int");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("SeasonTeamDAO");
                });

            modelBuilder.Entity("Data.DAO.GameDAO", b =>
                {
                    b.HasOne("Data.DAO.TeamDAO", "Away")
                        .WithMany()
                        .HasForeignKey("AwayId");

                    b.HasOne("Data.DAO.CompetitionDAO", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId");

                    b.HasOne("Data.DAO.TeamDAO", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("Data.DAO.SeasonTeamDAO", b =>
                {
                    b.HasOne("Data.DAO.CompetitionDAO", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId");

                    b.HasOne("Data.DAO.TeamDAO", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
